services:
  rethinkdb:
    container_name: rethinkdb
    image: rethinkdb:2.4.2
    restart: unless-stopped
    volumes:
        - "rethinkdb-data:/data"
    ports:
      - "8080:8080"  # Expose the RethinkDB web interface
      - "28015:28015"  # Expose the RethinkDB driver port (optional)
      - "29015:29015"  # Expose the RethinkDB cluster port (optional)
    command: "rethinkdb --bind all --cache-size 2048"

  adb:
    container_name: adb
    image: devicefarmer/adb:latest
    restart: unless-stopped
    volumes: 
      - "/dev/bus/usb:/dev/bus/usb"
    privileged: true

  stf:
    container_name: stf
    image: customstf
    ports:
      - "7100:7100"
      - "7110:7110"
      - "7400-7500:7400-7500"
    environment:
      - TZ='America/Los_Angeles'
      - RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
      - STF_ADMIN_EMAIL=admin@fakedomain.com
      - STF_ADMIN_NAME=admin
    restart: unless-stopped
    command: stf local --adb-host adb --public-ip 127.0.0.1 --provider-min-port 7400 --provider-max-port 7500

  db:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted

volumes:
  rethinkdb-data: {}
